server.port: 8070

spring:
  application:
    name: message-system
  datasource:
    source:
      hikari:
        jdbc-url: jdbc:mysql://localhost:13306/chat?useSSL=false&allowPublicKeyRetrieval=true
        username: dev_user
        password: dev_password
        driver-class-name: com.mysql.cj.jdbc.Driver
        pool-name: SourceConnectionPool
        minimum-idle: 10
        maximum-pool-size: 20
        idle-timeout: 60000
        connection-timeout: 30000

    replica:
      hikari:
        jdbc-url: jdbc:mysql://localhost:13307/chat?useSSL=false&allowPublicKeyRetrieval=true
        username: dev_user
        password: dev_password
        driver-class-name: com.mysql.cj.jdbc.Driver
        pool-name: ReplicaConnectionPool
        minimum-idle: 10
        maximum-pool-size: 20
        idle-timeout: 60000
        connection-timeout: 30000

    source-message1:
      hikari:
        jdbc-url: jdbc:mysql://localhost:13308/chat?useSSL=false&allowPublicKeyRetrieval=true
        username: dev_user
        password: dev_password
        driver-class-name: com.mysql.cj.jdbc.Driver
        pool-name: SourceMessage1ConnectionPool
        minimum-idle: 10
        maximum-pool-size: 20
        idle-timeout: 60000
        connection-timeout: 30000

    replica-message1:
      hikari:
        jdbc-url: jdbc:mysql://localhost:13309/chat?useSSL=false&allowPublicKeyRetrieval=true
        username: dev_user
        password: dev_password
        driver-class-name: com.mysql.cj.jdbc.Driver
        pool-name: ReplicaMessage1ConnectionPool
        minimum-idle: 10
        maximum-pool-size: 20
        idle-timeout: 60000
        connection-timeout: 30000

    source-message2:
      hikari:
        jdbc-url: jdbc:mysql://localhost:13310/chat?useSSL=false&allowPublicKeyRetrieval=true
        username: dev_user
        password: dev_password
        driver-class-name: com.mysql.cj.jdbc.Driver
        pool-name: SourceMessage2ConnectionPool
        minimum-idle: 10
        maximum-pool-size: 20
        idle-timeout: 60000
        connection-timeout: 30000

    replica-message2:
      hikari:
        jdbc-url: jdbc:mysql://localhost:13311/chat?useSSL=false&allowPublicKeyRetrieval=true
        username: dev_user
        password: dev_password
        driver-class-name: com.mysql.cj.jdbc.Driver
        pool-name: ReplicaMessage2ConnectionPool
        minimum-idle: 10
        maximum-pool-size: 20
        idle-timeout: 60000
        connection-timeout: 30000

  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true

  sql.init.mode: never

  data:
    redis:
      cluster:
        nodes:
          - localhost:6380
          - localhost:6381
          - localhost:6382
          - localhost:6383
          - localhost:6384
          - localhost:6385
      repositories:
        enabled: false

  kafka:
    bootstrap-servers: localhost:19094, localhost:19095, localhost:19096
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      properties:
        delivery.timeout.ms: 10000
        request.timeout.ms: 3000
        retry.backoff.ms: 100
    consumer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      auto-offset-reset: latest
      properties:
        allow.auto.create.topics: false
        enable.auto.commit: false
        partition.assignment.strategy: org.apache.kafka.clients.consumer.CooperativeStickyAssignor

message-system:
  kafka:
    topics:
      push: push-notification
    listeners:
      message:
        topic: message-relay
        group-id: relay-group
        concurrency: 3
      request:
        topic: message-request
        group-id: request-group
        concurrency: 3

logging:
  level:
    org.hibernate.orm.jdbc.bind: trace
    sun.rmi: info
    javax.management: info
    root: info
